site_name: Discourse Documentation
theme:
  name: material
  features:
    - navigation.instant
    - navigation.instant.preview
    - navigation.tracking
    - navigation.expand
    - navigation.path
    - navigation.top
    - search.suggest
    - search.highlight
plugins:
  - search
repo_url: https://github.com/hlashbrooke/docs-testing